### PR TITLE
Added MNIST and CIFAR10 dataloader funcs

### PR DESCRIPTION
**Pull request by Zymrael**
Hello!

I was trying to test some RandWireNNs but did not have enough compute available to prototype and quickly iterate with different random graphs on ImageNet. I decided to add MNIST and CIFAR10 support to allow for much easier experimentation. I suppose this might come in handy to other people trying to do the same.

MNIST comes with standard normalization transfs whereas CIFAR10 is raw (directly from https://www.cs.toronto.edu/~kriz/cifar.html). Additionally, the MNIST loader function directly downloads the dataset to ./data folder.

### CODE REVIEW

**Comment by seungwonpark** [comment]
Hi there! The features that you’ve added looks great to me, too. Lightweight tasks like MNIST/CIFAR10 will be viable for more users than ImageNet.
I would like to review this PR ASAP, but currently I’m not accesible to my computer for reviewing. (I’m typing this comment with my phone) Would you mind waiting for my review until tomorrow evening?
Plus, it’ll be more useful if you add the training results.

**Comment by Zymrael** [comment]
Thank you for the quick reply!
I'll submit another PR with some training results as soon as possible. It might take a couple of days since I'm currently rather busy.
Great work with your implementation btw

**Review by seungwonpark — CHANGES_REQUESTED** [review]
Some points:
- I think we should not contain downloaded MNIST/CIFAR10 data here, since it will make our repository heavy.
- Can you explain what does `MNIST-CIFAR10 loaders.ipynb` do, and why we need it?

**Comment by Zymrael** [comment]
I agree with the first point. The jupyter notebook was just me testing the dataloaders, I'll remove it.
I removed the data, `MNIST-CIFAR10 loaders.ipynb` and added a new bool arg to `MNIST_dataloader` to choose whether or not to download a new instance of the dataset.

**Review by seungwonpark — APPROVED** [review]

**Comment by seungwonpark** [comment]
LGTM. In order to prevent large files from being kept in git history, I'll squash merge it. (I'm not sure squash merge will be the solution, otherwise I'll use something like [git cleaner](https://stackoverflow.com/a/17890278) -- EDIT: Fortunately, squash merging worked out!)
Thank you!

**Pull request merged**
